# Generated by Django 4.1.3 on 2022-11-20 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='test', max_length=100, null=True)),
                ('province', models.CharField(default='test', max_length=60, null=True)),
                ('ministry', models.CharField(default='test', max_length=60, null=True)),
                ('code', models.CharField(default='test', max_length=7, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(upload_to='document %Y%m%d')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_app.employee')),
            ],
        ),
    ]
