# Generated by Django 3.2.16 on 2022-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_app.ministry'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general_app.province'),
        ),
    ]
