# Generated by Django 3.2.16 on 2022-12-09 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_auto_20221207_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='delete_date_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sender_mail_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_app.ministry'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_app.province'),
        ),
    ]
