# Generated by Django 4.1.1 on 2022-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0003_alter_certificatefile_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
