# Generated by Django 3.2.16 on 2022-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0004_auto_20221211_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefile',
            name='cert',
            field=models.FileField(upload_to='%Y'),
        ),
    ]
