# Generated by Django 4.1.1 on 2022-11-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0004_remove_employee_email_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
