# Generated by Django 4.1.1 on 2022-11-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0005_remove_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatefile',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
