# Generated by Django 3.2.16 on 2022-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0006_alter_certificatefile_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='is_upload',
            field=models.BooleanField(default=0),
        ),
    ]
