# Generated by Django 4.1.1 on 2022-11-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0006_certificatefile_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefile',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
