# Generated by Django 4.1.1 on 2022-11-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0007_alter_certificatefile_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ministry',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
