# Generated by Django 4.1.1 on 2022-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0008_alter_employee_code_alter_employee_ministry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
