# Generated by Django 3.2.16 on 2022-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0008_auto_20221217_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='is_upload',
        ),
        migrations.AddField(
            model_name='certificatefile',
            name='count_download',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='certificatefile',
            name='is_upload',
            field=models.BooleanField(default=0),
        ),
    ]
