# Generated by Django 4.1.3 on 2022-11-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0010_alter_employee_code_alter_employee_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cal_date',
            field=models.DateField(null=True),
        ),
    ]
