# Generated by Django 3.2.16 on 2022-12-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0010_auto_20221218_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='name',
        ),
    ]
