# Generated by Django 3.2.16 on 2022-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0012_user_detail_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='password',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
