# Generated by Django 3.2.16 on 2023-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0013_user_detail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefile',
            name='cert',
            field=models.FileField(max_length=200, upload_to='%Y/'),
        ),
    ]
