# Generated by Django 4.1.3 on 2022-11-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0013_alter_employee_cal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cal_date',
            field=models.DateField(),
        ),
    ]
