# Generated by Django 4.1.3 on 2022-11-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0014_alter_employee_cal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
