# Generated by Django 3.2.16 on 2023-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0014_alter_certificatefile_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='is_show',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
