# Generated by Django 3.2.16 on 2022-11-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0015_employee_send_email'),
    ]

    operations = [
        migrations.RenameModel('Employee','User_Detail')
    ]
