# Generated by Django 3.2.16 on 2023-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0015_province_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='is_show',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
