# Generated by Django 3.2.16 on 2022-11-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0016_auto_20221127_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefile',
            name='cert',
            field=models.FileField(upload_to='document %Y/%m/%d'),
        ),
    ]
