# Generated by Django 3.2.16 on 2023-01-07 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_app', '0016_ministry_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify_Certificatefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(max_length=200, upload_to='verify_certificate/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('editing_message', models.TextField(null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
