# Generated by Django 3.2.16 on 2023-01-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0017_verify_certificatefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_certificatefile',
            name='editing_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
