# Generated by Django 3.2.16 on 2023-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0018_alter_verify_certificatefile_editing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify_certificatefile',
            name='editing_message',
            field=models.TextField(null=True),
        ),
    ]
