# Generated by Django 3.2.16 on 2023-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0019_alter_verify_certificatefile_editing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_certificatefile',
            name='user_create',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
