# Generated by Django 3.2.16 on 2022-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0024_alter_certificatefile_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_date', models.IntegerField(default=3)),
                ('sent_mail_date', models.IntegerField(default=-2)),
            ],
        ),
    ]
