# Generated by Django 3.2.16 on 2022-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0026_rename_sent_mail_date_configuration_send_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='sender_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
