# Generated by Django 3.2.16 on 2022-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0027_configuration_sender_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='sender_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
