# Generated by Django 3.2.16 on 2022-12-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0028_alter_configuration_sender_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_detail',
            name='ministry_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_app.ministry'),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='province_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_app.province'),
        ),
    ]
